[graphics]
width = 1920
height = 1080
fullscreen = true

[audio]
music_volume = 15
sound_volume = 85

[input]
    [input.keyboard]
    enabled = true
    up = "W"
    down = "S"
    left = "A"
    right = "D"
    rotate_left = "J"
    rotate_right = "L"
    drop = "K"
    swap = "I"
    pause = "Space"

    [input.gamepad]
    enabled = true
    controller = "One"
    up = "DPadUp"
    down = "DPadDown"
    left = "DPadLeft"
    right = "DPadRight"
    rotate_left = "ButtonsA"
    rotate_right = "ButtonsB"
    drop = "ButtonsLeftShoulder"
    swap = "ButtonsRightShoulder"
    pause = "ButtonsStart"
